# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(662, 341)
        MainWindow.setStyleSheet("background-color: rgb(184, 184, 184);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonClose = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonClose.setGeometry(QtCore.QRect(20, 280, 621, 42))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButtonClose.setFont(font)
        self.pushButtonClose.setObjectName("pushButtonClose")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 8, 90, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonUpdateBedCount = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButtonUpdateBedCount.setFont(font)
        self.pushButtonUpdateBedCount.setObjectName("pushButtonUpdateBedCount")
        self.verticalLayout.addWidget(self.pushButtonUpdateBedCount)
        self.pushButtonFlowIntention = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButtonFlowIntention.setFont(font)
        self.pushButtonFlowIntention.setObjectName("pushButtonFlowIntention")
        self.verticalLayout.addWidget(self.pushButtonFlowIntention)
        self.pushButtonBroadRate = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButtonBroadRate.setFont(font)
        self.pushButtonBroadRate.setObjectName("pushButtonBroadRate")
        self.verticalLayout.addWidget(self.pushButtonBroadRate)
        self.pushButtonLatency = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.pushButtonLatency.setFont(font)
        self.pushButtonLatency.setObjectName("pushButtonLatency")
        self.verticalLayout.addWidget(self.pushButtonLatency)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(140, 8, 98, 241))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(270, 9, 261, 240))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalSliderBedCount = QtWidgets.QSlider(self.layoutWidget2)
        self.horizontalSliderBedCount.setMaximum(1200)
        self.horizontalSliderBedCount.setSingleStep(100)
        self.horizontalSliderBedCount.setPageStep(100)
        self.horizontalSliderBedCount.setSliderPosition(3)
        self.horizontalSliderBedCount.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderBedCount.setObjectName("horizontalSliderBedCount")
        self.verticalLayout_3.addWidget(self.horizontalSliderBedCount)
        self.horizontalSliderFlowIntention = QtWidgets.QSlider(self.layoutWidget2)
        self.horizontalSliderFlowIntention.setMinimum(-300)
        self.horizontalSliderFlowIntention.setMaximum(300)
        self.horizontalSliderFlowIntention.setSingleStep(0)
        self.horizontalSliderFlowIntention.setPageStep(0)
        self.horizontalSliderFlowIntention.setProperty("value", 300)
        self.horizontalSliderFlowIntention.setSliderPosition(300)
        self.horizontalSliderFlowIntention.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderFlowIntention.setObjectName("horizontalSliderFlowIntention")
        self.verticalLayout_3.addWidget(self.horizontalSliderFlowIntention)
        self.horizontalSliderBroadRate = QtWidgets.QSlider(self.layoutWidget2)
        self.horizontalSliderBroadRate.setMaximum(100)
        self.horizontalSliderBroadRate.setSingleStep(0)
        self.horizontalSliderBroadRate.setPageStep(0)
        self.horizontalSliderBroadRate.setProperty("value", 80)
        self.horizontalSliderBroadRate.setSliderPosition(80)
        self.horizontalSliderBroadRate.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderBroadRate.setObjectName("horizontalSliderBroadRate")
        self.verticalLayout_3.addWidget(self.horizontalSliderBroadRate)
        self.horizontalSliderLatency = QtWidgets.QSlider(self.layoutWidget2)
        self.horizontalSliderLatency.setMinimum(1)
        self.horizontalSliderLatency.setMaximum(30)
        self.horizontalSliderLatency.setSingleStep(0)
        self.horizontalSliderLatency.setPageStep(0)
        self.horizontalSliderLatency.setProperty("value", 14)
        self.horizontalSliderLatency.setSliderPosition(14)
        self.horizontalSliderLatency.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSliderLatency.setObjectName("horizontalSliderLatency")
        self.verticalLayout_3.addWidget(self.horizontalSliderLatency)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(560, 0, 101, 241))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.labelBedIncrement = QtWidgets.QLabel(self.layoutWidget3)
        self.labelBedIncrement.setObjectName("labelBedIncrement")
        self.verticalLayout_4.addWidget(self.labelBedIncrement)
        self.labelFlowIntention = QtWidgets.QLabel(self.layoutWidget3)
        self.labelFlowIntention.setObjectName("labelFlowIntention")
        self.verticalLayout_4.addWidget(self.labelFlowIntention)
        self.labelBroadRate = QtWidgets.QLabel(self.layoutWidget3)
        self.labelBroadRate.setObjectName("labelBroadRate")
        self.verticalLayout_4.addWidget(self.labelBroadRate)
        self.labelLatency = QtWidgets.QLabel(self.layoutWidget3)
        self.labelLatency.setObjectName("labelLatency")
        self.verticalLayout_4.addWidget(self.labelLatency)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "病毒扩散参数设置"))
        self.pushButtonClose.setText(_translate("MainWindow", "关闭病毒扩散仿真器"))
        self.pushButtonUpdateBedCount.setText(_translate("MainWindow", "更新"))
        self.pushButtonFlowIntention.setText(_translate("MainWindow", "更新"))
        self.pushButtonBroadRate.setText(_translate("MainWindow", "更新"))
        self.pushButtonLatency.setText(_translate("MainWindow", "更新"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; color:#0000ff;\">增加床位</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; color:#fc02ff;\">流动意向</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; color:#fc0107;\">传播概率</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; color:#ffff0a;\">潜伏期</span></p></body></html>"))
        self.labelBedIncrement.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt; color:#0000ff;\">0</span></p></body></html>"))
        self.labelFlowIntention.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt; color:#fc02ff;\">3</span></p></body></html>"))
        self.labelBroadRate.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt; color:#fc0107;\">0.8</span></p></body></html>"))
        self.labelLatency.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:24pt; color:#ffff0a;\">14</span></p></body></html>"))

